version: '3.4'

services:
  webtechnology:
    image: webtechnology
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
